# Generated by Django 2.2.7 on 2019-11-24 18:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('ON_WAY', 'ON_WAY'), ('NEAR', 'NEAR'), ('STARTED', 'STARTED')], max_length=15, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('pickup_address', models.CharField(blank=True, max_length=50, null=True)),
                ('start_pickup_location_type', models.CharField(blank=True, max_length=15, null=True)),
                ('start_pickup_location_latitude', models.FloatField(blank=True, null=True)),
                ('start_pickup_location_longitude', models.FloatField(blank=True, null=True)),
                ('end_pickup_location_type', models.CharField(blank=True, max_length=15, null=True)),
                ('end_pickup_location_latitude', models.FloatField(blank=True, null=True)),
                ('end_pickup_location_longitude', models.FloatField(blank=True, null=True)),
                ('passenger_first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('passenger_last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('driver_first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('driver_last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('driver_location_type', models.CharField(blank=True, max_length=15, null=True)),
                ('driver_location_latitude', models.FloatField(blank=True, null=True)),
                ('driver_location_longitude', models.FloatField(blank=True, null=True)),
                ('car_plate', models.CharField(blank=True, max_length=6, null=True)),
                ('check_code', models.CharField(blank=True, max_length=5, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.country')),
            ],
        ),
    ]
