# Generated by Django 2.2.7 on 2019-11-24 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20191124_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='trips.City'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.Country'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(blank=True, choices=[('onWay', 'onWay'), ('near', 'near'), ('started', 'started')], max_length=15, null=True),
        ),
    ]
